### ISSUE TITLE
Lord kicked out of house of lords during uprising?

### ISSUE THREAD

**Issue by HarrisonBacordo** [seanKenkeremath/lords-and-lads#16]
Am I correct to assume that if at any point during an uprising, the house of lords is cleared (e.g. lord drops the hammer), the uprising is considered complete and is nailed all the way through? Or can the uprising continue even though there is an empty house of lords?

**Comment by seanKenkeremath** [comment]
@HarrisonBacordo apologies for such a late response -- I need to turn on notifications for these

There's no rule saying the uprising nail is removed if the house of lords empties. The nail remains in play and players can still call uprising to try and hit the nail. If the nail is finished while no lords are active nothing happens.

A good example of why you might want to do this is if the uprising nail is 90% finished and you are close to becoming a lord. You may want to just squash the uprising before taking your seat.

Curious your thoughts on that. I personally like it the way it is because it adds a bit of extra politics and strategy

**Comment by austenlux** [comment]
I'm in favor of keeping the uprising nail active even if the house of lords empties. That way you could have it 90% done, then the house of lords empties, and you just save that uprising until more people become Lords and then finish the uprising. And you of course run the risk of what Sean said, where a person may do multiple flips/swings to finish the uprising and then their own Lad nail in the same turn. Makes the game more interesting/fun IMO.
