### ISSUE TITLE
Open AI ChatGPT thinks players should drink two instead of one for dropping the hammer

### ISSUE THREAD

**Issue by seanKenkeremath** [seanKenkeremath/lords-and-lads#22]
I asked Open AI's ChatGPT bot to add an additional rule to this game and it said:

> An additional rule for the game could be that if a player fails to catch the hammer after flipping it, they must take two drinks instead of just one. This would add an extra layer of difficulty to the game and make it more challenging for players, as they would need to be more careful and precise when flipping the hammer in order to avoid having to take extra drinks. Additionally, this rule would incentivize players to try and flip the hammer with more vertical flips, as doing so would give them more chances to strike the nail and avoid having to take extra drinks.

This AI has been trained with all of our society's combined knowledge. Its wisdom is beyond our understanding, and I am inclined to agree that we should take two drinks. Thoughts?

**Comment by mja2as** [comment]
counterproposal: take the same number of drinks as number of attempted flips. Drop on 1 flip = 1 drink. Go for a triple and botch it? 3 drinks

**Comment by seanKenkeremath** [comment]
the bot thinks we should do the opposite to encourage people to do more flips

> Additionally, this rule would incentivize players to try and flip the hammer with more vertical flips, as doing so would give them more chances to strike the nail and avoid having to take extra drinks.

I.e. it's the same risk to do multiple flips as it is to do one in terms of drinks which I think is a good design; You are already risking dropping the hammer in general by multi-flipping and likely getting a worse grip. I don't feel like you should be punished with extra drinks too

**Comment by austenlux** [comment]
I'm not really following that last sentence's logic:
>Additionally, this rule would incentivize players to try and flip the hammer with more vertical flips, as doing so would give them more chances to strike the nail and avoid having to take extra drinks.

That's always true regardless of the dropped hammer punishment. If there is any incentive changed, I kinda feel like it would be the opposite. Increasing the punishment for a dropped hammer might make people play it safer with only single flips to avoid harder catches.

But either way, since the drinking part of the game is always optional, and not measurable, I don't think tweaking the drinks has any significant impact on gameplay one way or another. So I'd be on board with this change, but I do kinda favor the high-risk high-reward aspect of Mark's counterproposal. That way each player has control over the level of punishment they may face.

I think it'd be good to ask that AI to come up with new rules that don't involve drinking, just the other game mechanics.

**Comment by seanKenkeremath** [comment]
Yeah, I agree that making it 2 instead of 1 in a practical sense does disincentivize multi-flips for that reason. It would  incentivize multi-flips in a world where people drop the hammer at an equal rate regardless of flip number which isn't the case. the bot isn't considering that. Scaling it up per flip would be even more of a deterrent though so we should not do that IMO

that said, I personally like upping the ante on drinks for a dropping the hammer in general, and this way we can say the game was balanced using state of the art AI

**Comment by seanKenkeremath** [comment]
I asked it a few times for other rules. Most of them are fine, but don't really add anything. now it's trying to get us to take a shot every time we drop the hammer

> In this variation, if a player fails to catch the hammer during the flip phase, they must take a shot of alcohol and immediately end their turn, passing the hammer to the next player in turn order. This rule adds an additional layer of difficulty and challenge to the game, and can make it even more exciting and entertaining for players.

**Comment by austenlux** [comment]
Fair, all good points. Let's do it.
